WebApp/Controllers/DiaDiemThamQuanController.cs
using Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Services;
using System.Security.Claims;
using WebApp.Common;

namespace WebApp.Controllers
{
    [Authorize(Roles = "root")]
    public class DiaDiemThamQuanController : Controller
    {
        private readonly ILogger<DiaDiemThamQuanController> _logger;
        private readonly IHoChieuHanhKhachService _hoChieuHanhKhachService;
        private readonly IConfiguration _configuration;
        private readonly UserManager<HC_IdentityUser> _userManager;

        public DiaDiemThamQuanController(ILogger<DiaDiemThamQuanController> logger
           , IHoChieuHanhKhachService hoChieuHanhKhachService
           , IConfiguration configuration
           , UserManager<HC_IdentityUser> userManager)
        {
            _logger = logger;
            _hoChieuHanhKhachService = hoChieuHanhKhachService;
            _configuration = configuration;
            _userManager = userManager;
        }
        public async Task<IActionResult> IndexAsync()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var roles = await _userManager.GetRolesAsync(user);
                ViewBag.TokenJWT = JwtCommon.GetToken(_configuration, user, roles);
            }

            return View();
        }
    }
}

WebApp/Controllers/HoChieuHanhKhachController.cs
using Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Services;
using System.Security.Claims;
using WebApp.Common;

namespace WebApp.Controllers
{
    [Authorize(Roles = "root")]
    public class HoChieuHanhKhachController : Controller
    {
        private readonly ILogger<HoChieuHanhKhachController> _logger;
        private readonly IHoChieuHanhKhachService _hoChieuHanhKhachService;
        private readonly IConfiguration _configuration;
        private readonly UserManager<HC_IdentityUser> _userManager;

        public HoChieuHanhKhachController(ILogger<HoChieuHanhKhachController> logger
            , IHoChieuHanhKhachService hoChieuHanhKhachService
            , IConfiguration configuration
            , UserManager<HC_IdentityUser> userManager)
        {
            _logger = logger;
            _hoChieuHanhKhachService = hoChieuHanhKhachService;
            _configuration = configuration;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userId1 = User.FindFirstValue(ClaimTypes.Sid);
            var user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var roles = await _userManager.GetRolesAsync(user);
                ViewBag.TokenJWT = JwtCommon.GetToken(_configuration, user, roles);
            }

            return View();
        }
    }
}

WebApp/Controllers/LanguagesController.cs
using Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Services;
using System.Data;
using System.Security.Claims;
using WebApp.Common;

namespace WebApp.Controllers
{
    [Authorize(Roles = "root")]
    public class LanguagesController : Controller
    {
        private readonly ILogger<LanguagesController> _logger;
        private readonly IHoChieuHanhKhachService _hoChieuHanhKhachService;
        private readonly IConfiguration _configuration;
        private readonly UserManager<HC_IdentityUser> _userManager;

        public LanguagesController(ILogger<LanguagesController> logger
           , IHoChieuHanhKhachService hoChieuHanhKhachService
           , IConfiguration configuration
           , UserManager<HC_IdentityUser> userManager)
        {
            _logger = logger;
            _hoChieuHanhKhachService = hoChieuHanhKhachService;
            _configuration = configuration;
            _userManager = userManager;
        }
        public async Task<IActionResult> Languages()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var roles = await _userManager.GetRolesAsync(user);
                ViewBag.TokenJWT = JwtCommon.GetToken(_configuration, user, roles);
            }

            return View();
        }
    }
}

WebApp/Controllers/QuocTichController.cs
using Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Services;
using System.Data;
using System.Security.Claims;
using WebApp.Common;

namespace WebApp.Controllers
{
    [Authorize(Roles = "root")]
    public class QuocTichController : Controller
    {
        private readonly ILogger<QuocTichController> _logger;
        private readonly IHoChieuHanhKhachService _hoChieuHanhKhachService;
        private readonly IConfiguration _configuration;
        private readonly UserManager<HC_IdentityUser> _userManager;

        public QuocTichController(ILogger<QuocTichController> logger
           , IHoChieuHanhKhachService hoChieuHanhKhachService
           , IConfiguration configuration
           , UserManager<HC_IdentityUser> userManager)
        {
            _logger = logger;
            _hoChieuHanhKhachService = hoChieuHanhKhachService;
            _configuration = configuration;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var roles = await _userManager.GetRolesAsync(user);
                ViewBag.TokenJWT = JwtCommon.GetToken(_configuration, user, roles);
            }
            return View();
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @* <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" /> *@
    <link href="~/lib/filepond/filepond.min.css" rel="stylesheet" />

    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>

    @*font-awesome*@
    <link href="https://fonts.googleapis.com/css2?family=Cabin:wght@400;500;600;700&family=Roboto:wght@100;300;400;500;700;900&display=swap"
          rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" rel="stylesheet" />

    @* jQuery *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @* datatable *@
    <script src="~/lib/DataTables/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="~/lib/DataTables/checkboxes.min.js" asp-append-version="true"></script>

    @* select2 *@
    <script src="~/lib/select2/select2.min.js" asp-append-version="true"></script>
    <link href="~/lib/select2/select2.min.css" rel="stylesheet">
    <link href="~/lib/select2/select2-bootstrap4.min.css" rel="stylesheet">

    @* datetimepicker *@
    <script src="~/lib/datetimepicker/moment-with-locales.min.js"></script>
    <script src="~/lib/datetimepicker/bootstrap-datetimepicker.min.js"></script>
    <link href="~/lib/datetimepicker/bootstrap-datetimepicker.min.css" rel="stylesheet">

    @*Filepond*@
    <script src="~/lib/filepond/filepond-plugin-file-validate-type.min.js"></script>
    <script src="~/lib/filepond/filepond.min.js"></script>
    <script src="~/lib/filepond/filepond.jquery.js"></script>

    @*ckeditor*@
    @*<script type="text/javascript" src="~/ckeditor/ckeditor.js"></script>*@

    <script src="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.0.1/ckeditor.js" type="text/javascript"></script>

</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-info bg-info">
        <partial name="_LoginPartial" />
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-info" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <a class="nav-link " asp-area="" asp-controller="Languages" asp-action="Languages">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Ngôn ngữ
                        </a>
                        <a class="nav-link " asp-area="" asp-controller="QuocTich" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Quốc tịch
                        </a>
                        <a class="nav-link " asp-area="" asp-controller="DiaDiemThamQuan" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Địa điểm tham quan
                        </a>
                        <a class="nav-link " asp-area="" asp-controller="HoChieuHanhKhach" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Hộ chiếu hành khách
                        </a>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Pages
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Authentication
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="login.html">Login</a>
                                        <a class="nav-link" href="register.html">Register</a>
                                        <a class="nav-link" href="password.html">Forgot Password</a>
                                    </nav>
                                </div>
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Error
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="401.html">401 Page</a>
                                        <a class="nav-link" href="404.html">404 Page</a>
                                        <a class="nav-link" href="500.html">500 Page</a>
                                    </nav>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                   
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    <main role="main" class="pb-3"
                        @RenderBody()
                    </main>
                </div>
            </main>
        </div>
    </div>
    <script src="~/views/layout/index.js"></script>
    <script src="~/js/scripts.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>